import type { BattleRole } from "./battleState";

// Every tunable battle number lives here so balancing is a one-file job.
export const BALANCE = {
  gaugeFillRate: 0.9,
  paralysisGaugePenaltyPerAlly: 0.2,
  minParalysisGaugeFactor: 0.4,
  paralysisCooldownFactor: 0.55,
  playerAttackDelay: 0.45,
  playerSyncDelay: 0.7,
  unityAttackDelay: 0.82,
  enemyAttackDelay: 0.55,
  enemySyncDelay: 0.75,
  enemyCooldownBase: 2.4,
  enemySyncCooldownBase: 3.1,
  enemyCooldownSpeedFactor: 1.6,
  stageMultiplier: 0.25,
  sameTypeBonus: 1.2,
  burnAttackPenalty: 0.82,
  syncBoostStacks: 4,
  syncBoostPerStack: 0.12,
  strikeRoleBonus: 1.12,
  techStatusBonus: 1.05,
  supportDamageReduction: 0.9,
  unityDamageScale: 0.62,
  unityPower: { strike: 42, tech: 34, support: 30 } as Record<BattleRole, number>,
  burnTickDamage: 5,
  poisonTickDamage: 7,
  baseStatusDuration: 5,
  techStatusDuration: 7,
  statusTickInterval: 1,
  varianceMin: 0.85,
  critChance: 1 / 16,
  critMultiplier: 1.5,
  syncCountdownMax: 3,
  paralysisBlockChance: 0.2,
  enemyHealThreshold: 0.45,
  enemyTrainerActionCooldown: 1.5,
  stageEnemyHpGrowth: 0.2,
  stageEnemyAttackGrowth: 0.14,
  stageEnemyDefenseGrowth: 0.11,
  allyLevelGrowth: 0.06,
  maxAllyLevel: 10,
  // Wild battles: one creature vs the team, so it gets a big HP pool.
  wildHpBase: 2.4,
  wildHpGrowth: 0.12,
  wildStatGrowth: 0.07,
  ballPower: { "poke-ball": 0.35, "great-ball": 0.6 } as Record<string, number>,
  captureHpWeight: 0.7,
  captureStatusBonus: 1.3,
  captureMinChance: 0.05,
  captureMaxChance: 0.95,
  holdBackCost: 1,
  holdBackHpFraction: 0.08,
  lastChanceCaptureMultiplier: 0.75,
  wildDropChance: 0.65,
  logLimit: 6,
  feedbackLimit: 10,
} as const;
