/** Deliberate movement choices for every bundled Kanto model. Walk/run are input
 * speeds; the species decides whether that means steps, flight, swimming, etc.
 * Amphibious bipeds stay on land; seals/fish use a swimming presentation. */
export type PokemonLocomotion = "biped" | "quadruped" | "fly" | "hover" | "swim" | "slither" | "crawl" | "hop" | "roll" | "ooze" | "burrow";
export const POKEMON_LOCOMOTION: Readonly<Record<number, PokemonLocomotion>> = {
  1: "quadruped", // bulbasaur
  2: "quadruped", // ivysaur
  3: "quadruped", // venusaur
  4: "biped", // charmander
  5: "biped", // charmeleon
  6: "fly", // charizard
  7: "biped", // squirtle
  8: "biped", // wartortle
  9: "biped", // blastoise
  10: "crawl", // caterpie
  11: "hop", // metapod
  12: "fly", // butterfree
  13: "crawl", // weedle
  14: "hop", // kakuna
  15: "fly", // beedrill
  16: "fly", // pidgey
  17: "fly", // pidgeotto
  18: "fly", // pidgeot
  19: "quadruped", // rattata
  20: "quadruped", // raticate
  21: "fly", // spearow
  22: "fly", // fearow
  23: "slither", // ekans
  24: "slither", // arbok
  25: "biped", // pikachu
  26: "biped", // raichu
  27: "biped", // sandshrew
  28: "biped", // sandslash
  29: "quadruped", // nidoran-f
  30: "quadruped", // nidorina
  31: "biped", // nidoqueen
  32: "quadruped", // nidoran-m
  33: "quadruped", // nidorino
  34: "biped", // nidoking
  35: "biped", // clefairy
  36: "biped", // clefable
  37: "quadruped", // vulpix
  38: "quadruped", // ninetales
  39: "biped", // jigglypuff
  40: "biped", // wigglytuff
  41: "fly", // zubat
  42: "fly", // golbat
  43: "biped", // oddish
  44: "biped", // gloom
  45: "biped", // vileplume
  46: "crawl", // paras
  47: "crawl", // parasect
  48: "biped", // venonat
  49: "fly", // venomoth
  50: "burrow", // diglett
  51: "burrow", // dugtrio
  52: "biped", // meowth
  53: "quadruped", // persian
  54: "biped", // psyduck
  55: "biped", // golduck
  56: "biped", // mankey
  57: "biped", // primeape
  58: "quadruped", // growlithe
  59: "quadruped", // arcanine
  60: "biped", // poliwag
  61: "biped", // poliwhirl
  62: "biped", // poliwrath
  63: "hover", // abra
  64: "biped", // kadabra
  65: "biped", // alakazam
  66: "biped", // machop
  67: "biped", // machoke
  68: "biped", // machamp
  69: "biped", // bellsprout
  70: "hop", // weepinbell
  71: "hop", // victreebel
  72: "swim", // tentacool
  73: "swim", // tentacruel
  74: "hover", // geodude
  75: "biped", // graveler
  76: "biped", // golem
  77: "quadruped", // ponyta
  78: "quadruped", // rapidash
  79: "quadruped", // slowpoke
  80: "biped", // slowbro
  81: "hover", // magnemite
  82: "hover", // magneton
  83: "fly", // farfetchd
  84: "biped", // doduo
  85: "biped", // dodrio
  86: "swim", // seel
  87: "swim", // dewgong
  88: "ooze", // grimer
  89: "ooze", // muk
  90: "swim", // shellder
  91: "swim", // cloyster
  92: "hover", // gastly
  93: "hover", // haunter
  94: "biped", // gengar
  95: "slither", // onix
  96: "biped", // drowzee
  97: "biped", // hypno
  98: "crawl", // krabby
  99: "crawl", // kingler
  100: "roll", // voltorb
  101: "roll", // electrode
  102: "hop", // exeggcute
  103: "biped", // exeggutor
  104: "biped", // cubone
  105: "biped", // marowak
  106: "biped", // hitmonlee
  107: "biped", // hitmonchan
  108: "biped", // lickitung
  109: "hover", // koffing
  110: "hover", // weezing
  111: "quadruped", // rhyhorn
  112: "biped", // rhydon
  113: "biped", // chansey
  114: "biped", // tangela
  115: "biped", // kangaskhan
  116: "swim", // horsea
  117: "swim", // seadra
  118: "swim", // goldeen
  119: "swim", // seaking
  120: "swim", // staryu
  121: "swim", // starmie
  122: "biped", // mr-mime
  123: "fly", // scyther
  124: "biped", // jynx
  125: "biped", // electabuzz
  126: "biped", // magmar
  127: "biped", // pinsir
  128: "quadruped", // tauros
  129: "swim", // magikarp
  130: "swim", // gyarados
  131: "swim", // lapras
  132: "ooze", // ditto
  133: "quadruped", // eevee
  134: "quadruped", // vaporeon
  135: "quadruped", // jolteon
  136: "quadruped", // flareon
  137: "hover", // porygon
  138: "crawl", // omanyte
  139: "crawl", // omastar
  140: "crawl", // kabuto
  141: "biped", // kabutops
  142: "fly", // aerodactyl
  143: "biped", // snorlax
  144: "fly", // articuno
  145: "fly", // zapdos
  146: "fly", // moltres
  147: "slither", // dratini
  148: "slither", // dragonair
  149: "fly", // dragonite
  150: "biped", // mewtwo
  151: "hover", // mew
};

export const isSuspended = (number: number) => ["fly", "hover", "swim"].includes(POKEMON_LOCOMOTION[number]);
